from __future__ import annotations

import json
import subprocess
import urllib.request
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, List, Protocol

from .io import load_claim_package, write_json, write_text

FORMALIZER_SCHEMA = "claimbench.formalizer_brief.v2.1"
LLM_SOURCE = "llm_proposed"


class FormalizerProvider(Protocol):
    def generate(self, brief: Dict[str, Any]) -> List[Dict[str, Any]]:
        ...


def _gate(status: str = "pass", reason: str = "LLM-proposed candidate; requires ClaimBench adjudication.") -> Dict[str, str]:
    return {
        "status": status,
        "source": LLM_SOURCE,
        "producer": "formalizer",
        "reason": reason,
    }


def _gates() -> Dict[str, Dict[str, str]]:
    gate_names = [
        "frozen_record",
        "span_grounding",
        "semantic_difference",
        "materiality",
        "minimal_change",
        "structure_preservation",
        "parity",
        "symmetry",
        "adversarial_review",
        "publication",
    ]
    return {name: _gate() for name in gate_names}


class MockFormalizer:
    """Offline deterministic formalizer for demos and tests.

    This is intentionally not a verifier and not a certifying adjudicator. It emits
    LLM-proposed formalizations with inconclusive verdicts unless the brief supplies
    explicit draft_verdict fields. The purpose is to exercise the v2.1 pipeline
    without pretending a model has proven the claim.
    """

    def generate(self, brief: Dict[str, Any]) -> List[Dict[str, Any]]:
        statement = str(brief.get("claim", {}).get("statement", ""))
        record = brief.get("claim", {}).get("record", []) or []
        spans = [str(x.get("id")) for x in record if x.get("id")]
        primary_span = spans[:1] or ["S1"]
        draft_verdict = str(brief.get("formalizer", {}).get("draft_verdict", "inconclusive")).lower()
        if draft_verdict not in {"pass", "fail", "inconclusive"}:
            draft_verdict = "inconclusive"
        canonical = {
            "id": "F1",
            "role": "canonical",
            "kind": "semantic",
            "description": f"Canonical draft formalization of: {statement}",
            "grounding_spans": primary_span,
            "changed_primitives": ["claim_statement"],
            "admission": {"status": "admitted", "gates": _gates(), "reason": "Generated by offline mock formalizer."},
            "verdict": {
                "status": draft_verdict,
                "summary": "Draft verdict supplied by formalizer brief or defaulted to inconclusive; not verifier-certified.",
                "metrics": {"formalizer_provider": "mock"},
            },
        }
        formalizations = [canonical]
        text = statement.lower()
        if any(term in text for term in ["budget", "safer", "better", "outperform", "compression"]):
            formalizations.append(
                {
                    "id": "F2",
                    "role": "alternative",
                    "kind": "semantic",
                    "description": "Adversarial draft alternative that isolates an ambiguous comparative primitive.",
                    "grounding_spans": spans[:2] or primary_span,
                    "changed_primitives": ["comparison_basis"],
                    "admission": {"status": "admitted", "gates": _gates(), "reason": "Generated as an adversarial semantic alternative by the mock formalizer."},
                    "verdict": {
                        "status": "inconclusive",
                        "summary": "Alternative reading requires verifier evidence before certification.",
                        "metrics": {"formalizer_provider": "mock", "candidate_boundary": True},
                    },
                }
            )
        return formalizations


class CommandFormalizer:
    """Adapter for local or remote LLM wrappers invoked as a command.

    The command receives the full formalizer brief on stdin as JSON and must return
    JSON in the shape {"formalizations": [...]} or a bare list of formalizations.
    """

    def __init__(self, command: str):
        self.command = command

    def generate(self, brief: Dict[str, Any]) -> List[Dict[str, Any]]:
        proc = subprocess.run(
            self.command,
            input=json.dumps(brief),
            text=True,
            shell=True,
            capture_output=True,
            check=False,
        )
        if proc.returncode != 0:
            raise RuntimeError(f"Formalizer command failed with code {proc.returncode}: {proc.stderr}")
        payload = json.loads(proc.stdout)
        if isinstance(payload, list):
            return payload
        return list(payload.get("formalizations", []))


class HTTPJSONFormalizer:
    """Generic HTTP JSON adapter for API-backed LLM formalizers.

    This avoids binding v2.1 to any one model provider. The endpoint receives the
    formalizer brief and must return {"formalizations": [...]}.
    """

    def __init__(self, endpoint: str, token: str | None = None):
        self.endpoint = endpoint
        self.token = token

    def generate(self, brief: Dict[str, Any]) -> List[Dict[str, Any]]:
        headers = {"Content-Type": "application/json"}
        if self.token:
            headers["Authorization"] = f"Bearer {self.token}"
        req = urllib.request.Request(
            self.endpoint,
            data=json.dumps(brief).encode("utf-8"),
            headers=headers,
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=120) as resp:  # nosec - user supplied endpoint for local/tool provider
            payload = json.loads(resp.read().decode("utf-8"))
        if isinstance(payload, list):
            return payload
        return list(payload.get("formalizations", []))


def provider_from_args(provider: str, command: str | None = None, endpoint: str | None = None, token: str | None = None) -> FormalizerProvider:
    if provider == "mock":
        return MockFormalizer()
    if provider == "command":
        if not command:
            raise ValueError("--command is required for provider=command")
        return CommandFormalizer(command)
    if provider == "http-json":
        if not endpoint:
            raise ValueError("--endpoint is required for provider=http-json")
        return HTTPJSONFormalizer(endpoint=endpoint, token=token)
    raise ValueError(f"Unknown formalizer provider: {provider}")


def build_package_from_brief(brief: Dict[str, Any], formalizations: List[Dict[str, Any]]) -> Dict[str, Any]:
    package = {
        "metadata": dict(brief.get("metadata", {}) or {}),
        "claim": dict(brief.get("claim", {}) or {}),
        "scope": dict(brief.get("scope", {}) or {}),
        "verifier": dict(brief.get("verifier", {}) or {}),
        "formalizations": formalizations,
        "evidence": dict(brief.get("evidence", {}) or {}),
    }
    package.setdefault("metadata", {})["formalizer_schema"] = FORMALIZER_SCHEMA
    package.setdefault("metadata", {})["generated_by"] = "claimbench_formalizer"
    return package


def formalize_brief(brief: Dict[str, Any], provider: FormalizerProvider) -> Dict[str, Any]:
    return build_package_from_brief(brief, provider.generate(brief))
